In [1]:
import pandas as pd

# 공공데이터 포털에서 다운로드 받은 bike02.csv퍼알 읽어오는 방법
df=pd.read_csv('greenData/bike02.csv',encoding='cp949')
df

           대여일자    대여건수
0    2025-07-01  132914
1    2025-07-02  151653
2    2025-07-03  151092
3    2025-07-04  151367
4    2025-07-05  118354
..          ...     ...
179  2025-12-27   42381
180  2025-12-28   40774
181  2025-12-29   66652
182  2025-12-30   71026
183  2025-12-31   55570

[184 rows x 2 columns]

In [5]:
import pandas as pd
df=pd.read_csv('greenData/bike02.csv',encoding='cp949')
df.head(10)

#pd.set_option('display.max_colums')
#pd.set_option()
#pd.set_option()

         대여일자    대여건수
0  2025-07-01  132914
1  2025-07-02  151653
2  2025-07-03  151092
3  2025-07-04  151367
4  2025-07-05  118354
5  2025-07-06  106785
6  2025-07-07  146664
7  2025-07-08  115371
8  2025-07-09  136307
9  2025-07-10  139733

In [22]:
df[df['대여건수']>=1000]

           대여일자    대여건수
0    2025-07-01  132914
1    2025-07-02  151653
2    2025-07-03  151092
3    2025-07-04  151367
4    2025-07-05  118354
..          ...     ...
179  2025-12-27   42381
180  2025-12-28   40774
181  2025-12-29   66652
182  2025-12-30   71026
183  2025-12-31   55570

[184 rows x 2 columns]

In [23]:
df.sort_values(by='대여건수',ascending=False)

           대여일자    대여건수
87   2025-09-26  176011
93   2025-10-02  175022
84   2025-09-23  173588
91   2025-09-30  170957
92   2025-10-01  169645
..          ...     ...
98   2025-10-07   26673
43   2025-08-13   26358
165  2025-12-13   19152
101  2025-10-10   13940
97   2025-10-06   10493

[184 rows x 2 columns]

In [24]:
total = df['대여건수'].sum()
avg = df['대여건수'].mean()
print(f"전체대여건수 합계 : {total:,}")
print(f"전체대여건수 평균 : {avg:,}")

전체대여건수 합계 : 19,647,762
전체대여건수 평균 : 106,781.31521739131

In [21]:
list = df.groupby('대여일자')['대여건수'].sum().sort_values(ascending=False)
print(list.index[0])

2025-09-26

In [26]:
df=pd.read_csv('greenData/pm10.csv',encoding='cp949')
df

                      일시   구분  미세먼지(PM10)  초미세먼지(PM25)
0       2024-12-31 23:00   평균        24.0         12.0
1       2024-12-31 23:00  강남구        18.0         10.0
2       2024-12-31 23:00  강동구        28.0         14.0
3       2024-12-31 23:00  강북구        16.0          9.0
4       2024-12-31 23:00  강서구        25.0         12.0
...                  ...  ...         ...          ...
228378   2024-01-01 0:00  용산구        35.0         25.0
228379   2024-01-01 0:00  은평구        21.0         15.0
228380   2024-01-01 0:00  종로구        28.0         26.0
228381   2024-01-01 0:00   중구        26.0         26.0
228382   2024-01-01 0:00  중랑구        28.0         23.0

[228383 rows x 4 columns]

In [29]:
#구분컬럼의데이터중'평균'인행을제외하여실제자치구데이터만남깁니다. (데이터전처리)
df.drop([0])

                      일시   구분  미세먼지(PM10)  초미세먼지(PM25)
1       2024-12-31 23:00  강남구        18.0         10.0
2       2024-12-31 23:00  강동구        28.0         14.0
3       2024-12-31 23:00  강북구        16.0          9.0
4       2024-12-31 23:00  강서구        25.0         12.0
5       2024-12-31 23:00  관악구        25.0         17.0
...                  ...  ...         ...          ...
228378   2024-01-01 0:00  용산구        35.0         25.0
228379   2024-01-01 0:00  은평구        21.0         15.0
228380   2024-01-01 0:00  종로구        28.0         26.0
228381   2024-01-01 0:00   중구        26.0         26.0
228382   2024-01-01 0:00  중랑구        28.0         23.0

[228382 rows x 4 columns]

In [49]:
#미세먼지(PM10) 농도가 25 이상이면서 동시에초미세먼지(PM25) 농도가 15 이상인 '주의 요망' 지역을찾습니다.
# 다중조건 and => & ,or => ** , not => ~
#disc = df[df['구분'] != 평균]
df[(df['미세먼지(PM10)']>=25) & (df['초미세먼지(PM25)']>=15)]
#condition = (disc['미세먼지(PM10)']>=25) & (disc['초미세먼지(PM25)']>=15)

          구분  미세먼지(PM10)  초미세먼지(PM25)
5        관악구        25.0         17.0
9        노원구        28.0         16.0
14      서대문구        31.0         16.0
15       서초구        31.0         15.0
19       양천구        25.0         15.0
...      ...         ...          ...
228377  영등포구        32.0         26.0
228378   용산구        35.0         25.0
228380   종로구        28.0         26.0
228381    중구        26.0         26.0
228382   중랑구        28.0         23.0

[104513 rows x 3 columns]

In [46]:
#조건에맞는지역의구분, 미세먼지(PM10), 초미세먼지(PM25) 컬럼만 선택해 출력하세요.


df[(df['미세먼지(PM10)']>=25) & (df['초미세먼지(PM25)']>=15)]

          구분  미세먼지(PM10)  초미세먼지(PM25)
5        관악구        25.0         17.0
9        노원구        28.0         16.0
14      서대문구        31.0         16.0
15       서초구        31.0         15.0
19       양천구        25.0         15.0
...      ...         ...          ...
228377  영등포구        32.0         26.0
228378   용산구        35.0         25.0
228380   종로구        28.0         26.0
228381    중구        26.0         26.0
228382   중랑구        28.0         23.0

[104513 rows x 3 columns]

In [53]:
df = pd.read_csv('greenData/accident.csv',encoding='cp949')
df

       사고년도        사고일자   사고시각    노선명  사고발생이정  방향  사망  부상    원인
0     2022년  2022-01-01  16:25    중앙선   145.2  부산   0   0  주시태만
1     2022년  2022-01-01  17:15  부산포항선    73.1  부산   0   0    졸음
2     2022년  2022-01-02  13:35    남해선   125.0  부산   0   2    과속
3     2022년  2022-01-02  15:10    남해선   104.0  순천   0   2    기타
4     2022년  2022-01-03   0:35    경부선   329.9  부산   0   0  주시태만
...     ...         ...    ...    ...     ...  ..  ..  ..   ...
4706  2024년  2024-12-29   5:55   서해안선   312.9  목포   0   1    기타
4707  2024년  2024-12-29   9:48  익산장수선     8.0  완주   0   1    과속
4708  2024년  2024-12-29  22:18    영동선    18.1  인천   0   0    기타
4709  2024년  2024-12-31  15:28  청주영덕선    62.7  상주   0   0    기타
4710  2024년  2024-12-31  19:34  무안광주선     4.7  무안   1   0  주시태만

[4711 rows x 9 columns]

In [54]:
df['사상자수'] = df['사망'] + df['부상']
df

       사고년도        사고일자   사고시각    노선명  사고발생이정  방향  사망  부상    원인  사상자수
0     2022년  2022-01-01  16:25    중앙선   145.2  부산   0   0  주시태만     0
1     2022년  2022-01-01  17:15  부산포항선    73.1  부산   0   0    졸음     0
2     2022년  2022-01-02  13:35    남해선   125.0  부산   0   2    과속     2
3     2022년  2022-01-02  15:10    남해선   104.0  순천   0   2    기타     2
4     2022년  2022-01-03   0:35    경부선   329.9  부산   0   0  주시태만     0
...     ...         ...    ...    ...     ...  ..  ..  ..   ...   ...
4706  2024년  2024-12-29   5:55   서해안선   312.9  목포   0   1    기타     1
4707  2024년  2024-12-29   9:48  익산장수선     8.0  완주   0   1    과속     1
4708  2024년  2024-12-29  22:18    영동선    18.1  인천   0   0    기타     0
4709  2024년  2024-12-31  15:28  청주영덕선    62.7  상주   0   0    기타     0
4710  2024년  2024-12-31  19:34  무안광주선     4.7  무안   1   0  주시태만     1

[4711 rows x 10 columns]

In [56]:
df.groupby('노선명')['사상자수'].sum().sort_values(ascending=False).head()

노선명
경부선      620
중부선      293
중부내륙선    279
영동선      274
서해안선     274
Name: 사상자수, dtype: int64

In [94]:
result = len(df[(df['원인']=='졸음')&(df['사망']>=1)])
print(result)

88

In [64]:
# form datetime import datetime
#pandas 에서 날짜를 추출하는 함수 종류
#CSV에 입력된 날짜는 문자열 데이터 타입이다.
# 날짜형식으로 형변환하는 함수 : datetime()

df = pd.read_csv('greenData/accident.csv',encoding='cp949')
df['사고일자'] = pd.to_datetime(df['사고일자'])
#사고일자의 월을 출력
# dt.month:월, dt.year:년, dt.day:일, dt.hour:시, dt.second:초, dt.minute:분
# dt.dayofweek : 요일을 숫자로 반환(0:월요일 ~ 6:일요일)
# dt.day_name() : 요일 이름이 문자열 ('Monday')
# dt.quarter : 분기(1분기 ~ 4분기)
df['사고월'] = df['사고일자'].dt.month
df

       사고년도       사고일자   사고시각    노선명  사고발생이정  방향  사망  부상    원인  사고월
0     2022년 2022-01-01  16:25    중앙선   145.2  부산   0   0  주시태만    1
1     2022년 2022-01-01  17:15  부산포항선    73.1  부산   0   0    졸음    1
2     2022년 2022-01-02  13:35    남해선   125.0  부산   0   2    과속    1
3     2022년 2022-01-02  15:10    남해선   104.0  순천   0   2    기타    1
4     2022년 2022-01-03   0:35    경부선   329.9  부산   0   0  주시태만    1
...     ...        ...    ...    ...     ...  ..  ..  ..   ...  ...
4706  2024년 2024-12-29   5:55   서해안선   312.9  목포   0   1    기타   12
4707  2024년 2024-12-29   9:48  익산장수선     8.0  완주   0   1    과속   12
4708  2024년 2024-12-29  22:18    영동선    18.1  인천   0   0    기타   12
4709  2024년 2024-12-31  15:28  청주영덕선    62.7  상주   0   0    기타   12
4710  2024년 2024-12-31  19:34  무안광주선     4.7  무안   1   0  주시태만   12

[4711 rows x 10 columns]

In [91]:
# groupby().count => 데이터가 비어있지 않은 값의 개수를 센다
# groupby().size() => 그룹별 전체 행의 개수를 센다.(비어있는 값도 개수센다)
result = df.groupby('사고월').size().sort_values(ascending=False)
print(f"가장 사고사 많은 월 {result.index[0]}월")
print(f"가장 사고사 많은 월 사고선수 {result}월")

result2 = df.groupby('사고월').size()
# idxmax() => 가장 큰 값이 들어있는 위치(인덱스 이름)에 접근하여 가져옴
maxMonth = result2.idxmax()
print(f"가장 사고사 많은 월 {result2}월")
print(f"가장 사고사 많은 월 사고선수 {maxMonth}월")

가장 사고사 많은 월 9월
가장 사고사 많은 월 사고선수 사고월
9     463
8     429
4     418
7     413
6     405
5     400
3     384
10    380
11    378
12    366
1     349
2     326
dtype: int64월
가장 사고사 많은 월 사고월
1     349
2     326
3     384
4     418
5     400
6     405
7     413
8     429
9     463
10    380
11    378
12    366
dtype: int64월
가장 사고사 많은 월 사고선수 9월